name: Pipeline

on:
  push:
    branches:
      - onion

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      docker:
        image: nikolaik/python-nodejs:latest
        options: --privileged
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install
        npm install -g graphviz
        sudo apt install graphviz
    
    - name: Add Graphviz to PATH
      run: echo "export PATH=\$PATH:/usr/local/bin" >> $GITHUB_ENV

    - name: Install Python dependencies
      run: |
          pip install diagrams

    - name: Start server
      run: (node app.js &) && sleep 5
    - name: Create Python code file
      run: |
        echo 'from diagrams import Diagram' > python_code.py
        echo 'from diagrams.k8s.clusterconfig import HPA' >> python_code.py
        echo 'from diagrams.k8s.compute import Deployment, Pod, ReplicaSet' >> python_code.py
        echo 'from diagrams.k8s.network import Ingress, Service' >> python_code.py
        echo '' >> python_code.py
        echo 'with Diagram("image", show=False):' >> python_code.py
        echo '    net = Ingress("domain.com") >> Service("svc")' >> python_code.py
        echo '    net >> [Pod("pod1"),' >> python_code.py
        echo '            Pod("pod2"),' >> python_code.py
        echo '            Pod("pod3")] << ReplicaSet("rs") << Deployment("dp") << HPA("hpa")' >> python_code.py


    - name: check GraphViz
      run: dot -V   
      
      
    - name: Send Python code
      run: |
        curl -X POST -H "Content-Type: text/plain" --data-binary @python_code.py http://localhost:3000/python-to-image

    - name: Wait for image file
      run: |
        sleep 5
    - name: Save generated image
      run: |
        if test -f "image.png"; then
          mv image.png $GITHUB_WORKSPACE/diagram.png
        fi

    - name: Check if diagram.png exists
      run: |
          ls -l $GITHUB_WORKSPACE/diagram.png

    - name: Upload artifacts
      if: success() && always() # Only run if previous steps were successful
      uses: actions/upload-artifact@v2
      with:
          name: diagrams
          path: ${{ github.workspace }}/diagram.png