name: Pipeline

on:
  push:
    branches:
      - onion

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      docker:
        image: nikolaik/python-nodejs:latest
        options: --privileged
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install
        npm install -g graphviz
    - name: Start server
      run: (node app.js &) && sleep 5
    - name: Send Python code
      run: |
        python_code='from diagrams import Diagram
                    from diagrams.aws.compute import EC2
                    from diagrams.aws.database import RDS
                    from diagrams.aws.network import ELB
                    with Diagram("image", show=False):
                          ELB("lb") >> EC2("web") >> RDS("userdb")'
        curl -X POST -H "Content-Type: text/plain" --data "$python_code" http://localhost:3000/python-to-image