name: Pipeline

on:
  push:
    branches:
      - onion

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      docker:
        image: nikolaik/python-nodejs:latest
        options: --privileged
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install
        npm install -g graphviz
    - name: Start server
      run: (node app.js &) && sleep 5
    - name: Send Python code
      run: |
        python_code='from diagrams import Diagram\nfrom diagrams.k8s.clusterconfig import HPA\nfrom diagrams.k8s.compute import Deployment, Pod, ReplicaSet\nfrom diagrams.k8s.network import Ingress, Service\n\nwith Diagram("image", show=False):\n    net = Ingress("domain.com") >> Service("svc")\n    net >> [Pod("pod1"),\n            Pod("pod2"),\n            Pod("pod3")] << ReplicaSet("rs") << Deployment("dp") << HPA("hpa")'
        echo $python_code | curl -X POST -H "Content-Type: text/plain" --data-binary @- http://localhost:3000/python-to-image