name: Pipeline

on:
  push:
    branches:
      - onion

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      docker:
        image: nikolaik/python-nodejs:latest
        options: --privileged
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2